Created Invite.yml
SidHacksCommunity/support pull request #163
Opened 2021-09-22 06:49 UTC by AbhijithGanesh

Automates invitation process
Addresses #162

2021-09-22 22:16 UTC, Panquesito7 requested changes

2021-09-22 22:16 UTC, Panquesito7 commented on .github/workflows/invite.yml
> +          comment: '<b>Invitation sent for the GitHub Organisation. Welcome to the CodXCrypt community 🎉</b>'
```suggestion
          comment: '<b>Invitation sent for the GitHub Organisation. Welcome to the SidHacks community! 🎉</b>'
```

2021-09-24 19:48 UTC, Panquesito7 approved these changes

2021-11-04 20:19 UTC, Panquesito7 commented
Ping. @siddharthdayalwal.

2021-11-04 20:21 UTC, siddharthdayalwal commented
Hey @Panquesito7 

Thanks for the ping! 

Could you automate it with the reply as you can see here: https://github.com/SidHacksCommunity/support/issues/2#issuecomment-891585321 ?

2021-11-04 20:42 UTC, Panquesito7 commented
> Hey @Panquesito7
> 
> Thanks for the ping!
> 
> Could you automate it with the reply as you can see here: [#2 (comment)](https://github.com/SidHacksCommunity/support/issues/2#issuecomment-891585321) ?

Should I open another PR for it or tell @AbhijithGanesh to update it?

2021-11-04 20:43 UTC, siddharthdayalwal commented
Let's wait for @AbhijithGanesh to jump in if he could do it before you do it. :)

2021-11-05 19:21 UTC, AbhijithGanesh commented
Can you tell me what I should do

2021-11-05 19:23 UTC, Panquesito7 commented
> Can you tell me what I should do

https://github.com/SidHacksCommunity/support/issues/2#issuecomment-891585321

2021-11-17 12:04 UTC, closed without merging